services:
  nginx:
    build: ./nginx
    ports:
      - 443:443/tcp
    volumes:
      - type: bind
        source: /path/to/sslcert.pem
        target: ./sslcert.pem
      - type: bind
        source: /path/to/sslcert.key
        target: ./sslcert.key
  server:
    build: ./
    volumes:
      - type: bind
        source: /path/to/ublog.db
        target: ./ublog.db
      - type: bind
        source: /path/to/site.json
        target: ./site.json
    command: serve
  ui:
    build: ./ui
    depends_on:
      - server
    environment:
      SITE_OWNER: Lancern
      SSR_DATA_URL: http://server:8000
      CSR_DATA_URL: https://lancern.xyz
